<?php /** 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5cc4adb8fe21c354b568ed16
*
* You will get 10% discount for each one of your friends
* 
*/
?>
<?php
	require_once './db/dbnotes_dbManager.php';
	
/*
 * SCHEMA DB Notebook
 * 
	{
		Title: {
			type: 'String'
		},
		//RELAZIONI
		
		
		//RELAZIONI ESTERNE
		
		Notebook: {
			type: Schema.ObjectId,
			ref : "User"
		},
		Notes: {
			type: Schema.ObjectId,
			ref : "Notebook"
		},
		
	}
 * 
 */


//CRUD METHODS


//CRUD - CREATE


$app->post('/notebook',	function () use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'Title'	=> isset($body->Title)?$body->Title:'',
		

		'Notes' => isset($body->Notes)?$body->Notes:'',
	);

	$obj = makeQuery("INSERT INTO notebook (_id, Title , Notes )  VALUES ( null, :Title , :Notes   )", $params, false);
        
	
	echo json_encode($body);
	
});
	
//CRUD - REMOVE

$app->delete('/notebook/:id',	function ($id) use ($app){
	
	$params = array (
		'id'	=> $id,
	);

	makeQuery("DELETE FROM notebook WHERE _id = :id LIMIT 1", $params);

});

//CRUD - FIND BY Notes

$app->get('/notebook/findByNotes/:key',	function ($key) use ($app){	

	$params = array (
		'key'	=> $key,
	);
	makeQuery("SELECT * FROM notebook WHERE Notes = :key", $params);
	
});
	
//CRUD - GET ONE
	
$app->get('/notebook/:id',	function ($id) use ($app){
	$params = array (
		'id'	=> $id,
	);
	
	$obj = makeQuery("SELECT * FROM notebook WHERE _id = :id LIMIT 1", $params, false);
	
	
	
	echo json_encode($obj);
	
});
	
	
//CRUD - GET LIST

$app->get('/notebook',	function () use ($app){
	makeQuery("SELECT * FROM notebook");
});


//CRUD - EDIT

$app->post('/notebook/:id',	function ($id) use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'id'	=> $id,
		'Title'	    => isset($body->Title)?$body->Title:''
,
		'Notes'      => isset($body->Notes)?$body->Notes:'' 
	);

	$obj = makeQuery("UPDATE notebook SET  Title = :Title  , Notes=:Notes  WHERE _id = :id LIMIT 1", $params, false);
        
	
	echo json_encode($body);
    	
});


/*
 * CUSTOM SERVICES
 *
 *	These services will be overwritten and implemented in  Custom.js
 */

			
?>